### ISSUE TITLE
For each plate calculation of the standard metrics that we have been doing do far in an excel table 

### ISSUE THREAD

**Issue by eleannakara** [alecrimi/cells_tools#2]
- Number of GFP+ cells per well (average 2 images) 
- Area 
- Normalized cell count (RFP+GFP-/GFP+) (specific way of calculation) 
- Mean intensity 
- RFP+GFP- cell count  
- Well number (A1, A2, A3 etc)  
- siRNA per well (csv file with siRNA in each well can be included as input together with the raw data)

**Comment by alecrimi** [comment]
it saves everything in CSV files (numeric and alphanumeric)
